name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your-image-name:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7  # Add or remove platforms as needed

      - name: Verify Image
        run: docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/your-image-name:latest
